/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.frames;

import com.data.Barang;//memanggil objek di kelas Barang.java (Polymorphism)
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.ParseException;//  untuk meng-handle atau menangani kesalahan saat parsing atau mengubah format tanggal dari String menjadi tanggal atau sebaliknya
import java.text.SimpleDateFormat;// library untuk menangani format tanggal dalam aplikasi
import java.util.ArrayList;// implementasi dari interface List yang menyediakan alur penyimpanan yang fleksibel. ArrayList dapat menampung duplikat dan memiliki ukuran yang dinamis
import java.util.Iterator; // library untuk melakukan iterasi atau mengulangi elemen dari koleksi yang telah diimplementasikan, seperti ArrayList
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;// library untuk menampilkan dialog box
import javax.swing.table.DefaultTableModel; // library untuk mengatur tabel di form
import javax.swing.table.TableModel; //Ini merupakan interface yang mengatur model data untuk JTable

/**
 *
 * @author ASUS
 */
public class InventorisBarangFrame extends javax.swing.JFrame {

    public ArrayList<Barang> dataBarang;// menginisialisasi konstruktor ArrayList untuk kelas Barang
    public int editedAt;// membuat ariable editedAt dengan tipe data integer

    /**
     * Creates new form InventorisBarangFrame
     */
    public InventorisBarangFrame() {// membuat konstruktor InventorisBarangFrame untuk pemanggilan beberapa method
        initComponents();// untuk menginisialisasikan semua komponennya
        this.dataBarang = new ArrayList<Barang>();
        this.editedAt = -1;// membuat value/nilai -1 untuk variabel editedAt
        this.refreshTable("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AppPanel = new javax.swing.JPanel();
        ContainerPanel = new javax.swing.JPanel();
        TitlePanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        FormPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        noTextField = new javax.swing.JTextField();
        kodeTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        keteranganTextField = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        jumlahTextField = new javax.swing.JTextField();
        tanggalButton = new com.toedter.calendar.JDateChooser();
        ActionPanel = new javax.swing.JPanel();
        tambahButton = new javax.swing.JButton();
        ubahButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        bersihButton = new javax.swing.JButton();
        keluarButton = new javax.swing.JButton();
        TablePanel = new javax.swing.JScrollPane();
        barangTable = new javax.swing.JTable();
        SearchPanel = new javax.swing.JPanel();
        cariTextField = new javax.swing.JTextField();
        cariButton = new javax.swing.JButton();
        resetCariButton = new javax.swing.JButton();
        importButton = new javax.swing.JButton();
        TablePanel1 = new javax.swing.JScrollPane();
        barangImport = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AppPanel.setBackground(new java.awt.Color(51, 0, 51));

        ContainerPanel.setBackground(new java.awt.Color(102, 0, 102));

        jLabel12.setText("INVENTARIS BARANG");

        javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
        TitlePanel.setLayout(TitlePanelLayout);
        TitlePanelLayout.setHorizontalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TitlePanelLayout.setVerticalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FormPanel.setBackground(new java.awt.Color(204, 0, 255));
        FormPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tambah Data"));

        jLabel13.setText("No");

        jLabel14.setText("Tanggal");

        jLabel15.setText("Kode Barang");

        jLabel16.setText("Nama Barang");

        noTextField.setBackground(new java.awt.Color(204, 153, 255));
        noTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                noTextFieldKeyPressed(evt);
            }
        });

        kodeTextField.setBackground(new java.awt.Color(204, 153, 255));
        kodeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kodeTextFieldKeyPressed(evt);
            }
        });

        keteranganTextField.setBackground(new java.awt.Color(204, 153, 255));
        keteranganTextField.setColumns(20);
        keteranganTextField.setRows(5);
        jScrollPane1.setViewportView(keteranganTextField);

        jLabel17.setText("Jumlah Barang");

        jLabel18.setText("Keterangan");

        namaTextField.setBackground(new java.awt.Color(204, 153, 255));

        jumlahTextField.setBackground(new java.awt.Color(204, 153, 255));

        tanggalButton.setBackground(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout FormPanelLayout = new javax.swing.GroupLayout(FormPanel);
        FormPanel.setLayout(FormPanelLayout);
        FormPanelLayout.setHorizontalGroup(
            FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormPanelLayout.createSequentialGroup()
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)))
                    .addGroup(FormPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(FormPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)))))
                .addGap(47, 47, 47)
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(kodeTextField)
                    .addComponent(noTextField)
                    .addComponent(namaTextField)
                    .addComponent(jumlahTextField)
                    .addComponent(tanggalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FormPanelLayout.setVerticalGroup(
            FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormPanelLayout.createSequentialGroup()
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17))
                    .addGroup(FormPanelLayout.createSequentialGroup()
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addComponent(tanggalButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jumlahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ActionPanel.setBackground(new java.awt.Color(204, 0, 255));

        tambahButton.setBackground(new java.awt.Color(153, 51, 255));
        tambahButton.setText("TAMBAH");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        ubahButton.setBackground(new java.awt.Color(153, 0, 255));
        ubahButton.setText("UBAH");
        ubahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahButtonActionPerformed(evt);
            }
        });

        hapusButton.setBackground(new java.awt.Color(153, 0, 255));
        hapusButton.setText("HAPUS");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        bersihButton.setBackground(new java.awt.Color(153, 0, 255));
        bersihButton.setText("BERSIH");
        bersihButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihButtonActionPerformed(evt);
            }
        });

        keluarButton.setBackground(new java.awt.Color(153, 0, 255));
        keluarButton.setText("KELUAR");
        keluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ActionPanelLayout = new javax.swing.GroupLayout(ActionPanel);
        ActionPanel.setLayout(ActionPanelLayout);
        ActionPanelLayout.setHorizontalGroup(
            ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tambahButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ubahButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bersihButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(keluarButton)
                .addGap(62, 62, 62))
        );
        ActionPanelLayout.setVerticalGroup(
            ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahButton)
                    .addComponent(ubahButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapusButton)
                    .addComponent(bersihButton))
                .addGap(18, 18, 18)
                .addComponent(keluarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        barangTable.setBackground(new java.awt.Color(102, 255, 102));
        barangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NO.", "Tanggal", "Kode Barang", "Nama Barang", "Jumlah Barang", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        barangTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barangTableMouseClicked(evt);
            }
        });
        TablePanel.setViewportView(barangTable);

        SearchPanel.setBackground(new java.awt.Color(51, 255, 51));
        SearchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Pencarian Data"));

        cariTextField.setBackground(new java.awt.Color(153, 255, 153));
        cariTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTextFieldActionPerformed(evt);
            }
        });

        cariButton.setBackground(new java.awt.Color(0, 153, 51));
        cariButton.setText("CARI");
        cariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariButtonActionPerformed(evt);
            }
        });

        resetCariButton.setBackground(new java.awt.Color(0, 153, 51));
        resetCariButton.setText("RESET");
        resetCariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetCariButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cariTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resetCariButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cariButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetCariButton)
                .addContainerGap())
        );

        importButton.setBackground(new java.awt.Color(0, 153, 51));
        importButton.setText("IMPORT");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        barangImport.setBackground(new java.awt.Color(102, 255, 102));
        barangImport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NO.", "Tanggal", "Kode Barang", "Nama Barang", "Jumlah Barang", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        barangImport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barangImportMouseClicked(evt);
            }
        });
        TablePanel1.setViewportView(barangImport);

        javax.swing.GroupLayout ContainerPanelLayout = new javax.swing.GroupLayout(ContainerPanel);
        ContainerPanel.setLayout(ContainerPanelLayout);
        ContainerPanelLayout.setHorizontalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContainerPanelLayout.createSequentialGroup()
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerPanelLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(importButton))
                    .addGroup(ContainerPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ContainerPanelLayout.createSequentialGroup()
                                .addComponent(FormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ActionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(TablePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        ContainerPanelLayout.setVerticalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerPanelLayout.createSequentialGroup()
                .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerPanelLayout.createSequentialGroup()
                        .addComponent(ActionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(importButton)
                .addGap(18, 18, 18)
                .addComponent(TablePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AppPanelLayout = new javax.swing.GroupLayout(AppPanel);
        AppPanel.setLayout(AppPanelLayout);
        AppPanelLayout.setHorizontalGroup(
            AppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AppPanelLayout.setVerticalGroup(
            AppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AppPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AppPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTextFieldKeyPressed

    private void kodeTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodeTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeTextFieldKeyPressed

    private Barang getFieldBarang() {// membuat objek Barang dengan method getFieldBarang untuk button tambah dan ubah
        Barang barang = null;// menginisialisasi kelas Barangnya
        try {
            String tampilan = "dd-MM-yyyy";// parameter untuk mengubah format tanggal
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);// membuat objek fm saat ini yg dipanggil dengan parameter tampilan
            String tanggal = String.valueOf(fm.format(tanggalButton.getDate()));// mengubah objek tanggal menjadi string yang telah diformat
            if (tanggal.equals("") || noTextField.getText().equals("") || kodeTextField.getText().equals("") || namaTextField.getText().equals("") || jumlahTextField.getText().equals("") || keteranganTextField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Data tidak boleh kosong !");// jika komponen TextFieldnya kosong, maka akan muncul pesan berikut
            } else {
                Barang tempBarang = new Barang(
                        Integer.parseInt(noTextField.getText()),
                        Integer.parseInt(jumlahTextField.getText()),
                        tanggal,
                        kodeTextField.getText(),
                        namaTextField.getText(),
                        keteranganTextField.getText()
                );
                barang = tempBarang;
            }
        } catch (NumberFormatException e) {// ini mengharuskan user menginput angka pada TextField No dan jumlah barang
            JOptionPane.showMessageDialog(this, "Jumlah dan No Harus Angka..! !");
        } catch (Exception e) {// mengharuskan user menginputkan semua data
            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong..! !");
        }
        return barang;
    }

    private void setFieldBarang() {// membuat method setFieldBarang
        try {
            Barang barang = this.dataBarang.get(this.editedAt);//memanggil kelas Barang
            noTextField.setText(String.valueOf(barang.no));
            jumlahTextField.setText(String.valueOf(barang.jumlah));
            namaTextField.setText(String.valueOf(barang.nama));
            kodeTextField.setText(String.valueOf(barang.kode));
            keteranganTextField.setText(String.valueOf(barang.keterangan));
            String tampilan = "dd-MM-yyyy";
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);
            tanggalButton.setDate(fm.parse(barang.tanggal));
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Format Tanggal Salah");//format tanggal hrs dd-MM-yyyy, jika tidak maka muncul pesan berikut
        }

    }

    private void refreshTable(String cari) {// membuat method refreshTable untuk mencari nama barang dengan variabel cari yg tipe datanya String
        DefaultTableModel model = (DefaultTableModel) barangTable.getModel();
        model.setRowCount(0);
        for (Barang barang : dataBarang) {
            if (barang.nama.toLowerCase().contains(cari)) {// disini jika yg dicari kolom nama barang, maka akan muncul barisnya
                Object[] row = new Object[6];//membuat array dengan variabel barang agar terurut
                row[0] = barang.no;
                row[1] = barang.tanggal;
                row[2] = barang.kode;
                row[3] = barang.nama;
                row[4] = barang.jumlah;
                row[5] = barang.keterangan;
                model.addRow(row);
            }
        }
    }

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        // TODO add your handling code here:
        Barang barang = this.getFieldBarang();//memanggil method getFieldBarang menggunakan kelas Barang
        if (barang != null) {
            this.dataBarang.add(barang);
            this.resetTextField();
            this.refreshTable("");
            JOptionPane.showMessageDialog(this, "Data Berhasil Dimasukkan..! !");//jika tambah data sesuai maka akan muncul pesan berikut saat ditambahkan
        
        String no = String.valueOf(barang.getNo());
        String tanggal = String.valueOf(barang.getTanggal());
        String kode = String.valueOf(barang.getKode());
        String nama = String.valueOf(barang.getNama());
        String jumlah = String.valueOf(barang.getJumlah());
        String keterangan = String.valueOf(barang.getKeterangan());
        
        String filePath = "simpan.txt";// saya menambahkan file simpan.txt di file projek untuk menyimpan database
        File file = new File (filePath);
        try (
            FileWriter fw = new FileWriter(file, true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter writer = new PrintWriter(bw)) {

            //dibawah ini untuk menampilkan databse di file .txt
            writer.println(no + "\t" + tanggal + "\t" + kode + "\t" + nama + "\t" + jumlah + "\t" + keterangan);

            for (int i = 0; i < barangTable.getRowCount(); i++) {
                for (int j = 0; j < barangTable.getColumnCount(); j++) {
                    writer.print(barangTable.getValueAt(i, j) + "\t");
                }
                writer.println();
            }
        } catch (IOException ex) {
            Logger.getLogger(InventorisBarangFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void resetTextField() {// membuat method resetTextField untuk membersihkan kolom komponen-komponennya
        noTextField.setText(null);
        jumlahTextField.setText(null);
        namaTextField.setText(null);
        kodeTextField.setText(null);
        keteranganTextField.setText(null);
        tanggalButton.setDate(null);
    }

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        // TODO add your handling code here:
        if (this.editedAt != -1) {// jika variable editedAt bernilai -1(tidak ada data yg dipilih satupun)
            this.dataBarang.remove(this.editedAt);
            this.resetTextField();
            this.refreshTable("");
            this.editedAt = -1;
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Data Terlebih Dahulu..! !");//ini mengharuskan user mengklik salah satu data dulu yg dipilih untuk di hapus
        }
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void barangTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangTableMouseClicked
        // TODO add your handling code here:
        try {
            int barisTerpilih = barangTable.getSelectedRow();
            if (barisTerpilih >= 0) {
                TableModel model = barangTable.getModel();
                int index = barisTerpilih;
                this.editedAt = index;
                this.setFieldBarang();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_barangTableMouseClicked

    private void cariTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cariTextFieldActionPerformed

    private void ubahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahButtonActionPerformed
        // TODO add your handling code here:
        if (this.editedAt != -1) {
            Barang barang = this.getFieldBarang();
            if (barang != null) {
                this.dataBarang.set(this.editedAt, barang);
                this.refreshTable("");
                this.resetTextField();
                this.editedAt = -1;
            }

        } else {
            JOptionPane.showMessageDialog(this, "Pilih Data Terlebih Dahulu..! !");// jika ingin mengubah data, maka harus di klik salah satu datanya dulu
        }
    }//GEN-LAST:event_ubahButtonActionPerformed

    private void bersihButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihButtonActionPerformed
        // TODO add your handling code here:
        this.resetTextField();// memanggil method resetTextField
    }//GEN-LAST:event_bersihButtonActionPerformed

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariButtonActionPerformed
        // TODO add your handling code here:
        String cari = cariTextField.getText();//membuat variabel cari dengan tipe data String pada TextField pencarian
        boolean isDisabled = false;
        if (cari.equals("")) {// jika variabel cari kosong,
            isDisabled = true;// maka tidak akan memunculkan apa-apa/ disable nya diaktifkan
        }
        tambahButton.setEnabled(isDisabled);//ini jika TextField cari di klik, maka button tambah, ubah, hapus akan unable
        hapusButton.setEnabled(isDisabled);
        ubahButton.setEnabled(isDisabled);
        barangTable.setEnabled(isDisabled);
        this.refreshTable(cari);// memanggil method refreshTable
    }//GEN-LAST:event_cariButtonActionPerformed

    private void keluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarButtonActionPerformed
        // TODO add your handling code here:
        dispose();//hampir sama seperti perintah System.exit, bedanya dispose ini untuk menutup form yg sedang dibuka, sedangkan System.exit itu untuk memberhentikan running semua form
    }//GEN-LAST:event_keluarButtonActionPerformed

    private void resetCariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetCariButtonActionPerformed
        // TODO add your handling code here:
        this.cariTextField.setText("");// disini jika tombol button reset di klik, maka buttom tambah, ubah, hapus akan aktif kembali
        tambahButton.setEnabled(true);
        hapusButton.setEnabled(true);
        ubahButton.setEnabled(true);
        barangTable.setEnabled(true);
        this.refreshTable("");
    }//GEN-LAST:event_resetCariButtonActionPerformed

    private void barangImportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangImportMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_barangImportMouseClicked

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        // TODO add your handling code here:
        String filePath = "simpan.txt";
        File file = new File(filePath);

        try (
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr)) {

            DefaultTableModel model = (DefaultTableModel) barangImport.getModel();
            model.setRowCount(0); // Menghapus data yang ada di dalam tabel

            String line;
            while ((line = br.readLine()) != null) {
            String[] data = line.split("\t"); // Assuming tab-separated values, adjust if needed

            // Assuming the structure of your data matches the columns in your table
            model.addRow(data);
        }

        } catch (FileNotFoundException ex) {
        Logger.getLogger(InventorisBarangFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
        Logger.getLogger(InventorisBarangFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_importButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventorisBarangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventorisBarangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventorisBarangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventorisBarangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventorisBarangFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActionPanel;
    private javax.swing.JPanel AppPanel;
    private javax.swing.JPanel ContainerPanel;
    private javax.swing.JPanel FormPanel;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JScrollPane TablePanel;
    private javax.swing.JScrollPane TablePanel1;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JTable barangImport;
    private javax.swing.JTable barangTable;
    private javax.swing.JButton bersihButton;
    private javax.swing.JButton cariButton;
    private javax.swing.JTextField cariTextField;
    private javax.swing.JButton hapusButton;
    private javax.swing.JButton importButton;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jumlahTextField;
    private javax.swing.JButton keluarButton;
    private javax.swing.JTextArea keteranganTextField;
    private javax.swing.JTextField kodeTextField;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField noTextField;
    private javax.swing.JButton resetCariButton;
    private javax.swing.JButton tambahButton;
    private com.toedter.calendar.JDateChooser tanggalButton;
    private javax.swing.JButton ubahButton;
    // End of variables declaration//GEN-END:variables
}
